# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5edf63702cba0c864a67b43241ed3d5264e2d72b5b6808f1fd991faf06eb582b72c9c7f4a6b4dea0ba80e880eb40efa1431d2fb35e85346cfb74395665877338

test:
  secret_key_base: fab51aa95665577b3f63e323c23bd6efa2951c2768c949010f3f2a02c24a0e2f3f94db90dd69f2f2797ddcceed5b958d03e681052f2cd5c820e195689e61f90e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
